{% set name = "svgsynoptic2" %}
{% set version = "4.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/svgsynoptic2-{{ version }}.tar.gz
  sha256: 791d6030e36aa2acd83c192ec37a4ad9067708754774ecf30c493cf1f3c2c4f7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - pyqtwebengine
    - pytango >=9.2.1
    - python >=3.6
    - setuptools
    - taurus >=4.5

test:
  imports:
    - svgsynoptic2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/MaxIV/lib-maxiv-svgsynoptic
  summary: Widget for displaying a SVG synoptic.
  description: |
    svgsynoptic2 is a library for creating control system synoptics using SVG.
    The library is developed with the TANGO control system in mind,
    and has a Qt widget implementation based on Taurus.
    It should however be possible to adapt it to other systems as well.
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  dev_url: https://gitlab.com/MaxIV/lib-maxiv-svgsynoptic

extra:
  recipe-maintainers:
    - beenje
